# Generated by Django 3.2.4 on 2021-08-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frypan', '0004_alter_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='full_price',
            new_name='discount_price',
        ),
    ]
