# Generated by Django 3.2.4 on 2021-08-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frypan', '0006_item_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='label_color',
        ),
    ]
