# Generated by Django 3.2.4 on 2021-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frypan', '0009_auto_20210901_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
